<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <UserSecretsId>fc24d3df-779a-489c-871e-10bb9965a9f2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions"  />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json"  />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets"  />
    <PackageReference Include="Microsoft.Extensions.Logging"  />
    <PackageReference Include="Microsoft.NET.Test.Sdk"  />
    <PackageReference Include="xunit"  />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\ReceiptRecognition.AzureAI\ReceiptRecognition.AzureAI.csproj" />
    <ProjectReference Include="..\Infrastructure\ReceiptRecognition.Ollama\ReceiptRecognition.Ollama.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Receipts\Shops\Aldi-mini.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Receipts\Shops\Aldi.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Receipts\Shops\AlpeBureau.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Receipts\Shops\Kiabi.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Receipts\GasStation\" />
    <Folder Include="Receipts\Restaurants\" />
  </ItemGroup>

</Project>
