<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>548b2635-5427-4001-80b2-f97e54b1d0ac</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aspire\ReceiptRecognition.ServiceDefaults\ReceiptRecognition.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Infrastructure\ReceiptRecognition.AzureAI\ReceiptRecognition.AzureAI.csproj" />
    <ProjectReference Include="..\Infrastructure\ReceiptRecognition.OllamaSharp\ReceiptRecognition.OllamaSharp.csproj" />
    <ProjectReference Include="..\Infrastructure\ReceiptRecognition.Ollama\ReceiptRecognition.Ollama.csproj" />
  </ItemGroup>

</Project>
