<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="OllamaSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ReceiptRecognition.Core\ReceiptRecognition.Core.csproj" />
  </ItemGroup>
</Project>
